replicaCount: 1
fullnameOverride: opencti-ci

env:
  APP__ADMIN__EMAIL: admin@opencti.io
  APP__ADMIN__PASSWORD: test
  APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
  APP__BASE_PATH: "/"
  APP__HEALTH_ACCESS_KEY: f93747ff-2ea1-4717-900c-9df20b8e4429
  APP__TELEMETRY__METRICS__ENABLED: true
  APP__GRAPHQL__PLAYGROUND__ENABLED: false
  APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION: false
  ELASTICSEARCH__ENGINE_SELECTOR: elk
  ELASTICSEARCH__URL: http://opencti-ci-elasticsearch:9200
  MINIO__ENDPOINT: opencti-ci-minio
  RABBITMQ__HOSTNAME: opencti-ci-rabbitmq
  RABBITMQ__PASSWORD: ChangeMe
  RABBITMQ__PORT_MANAGEMENT: 15672
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: user
  REDIS__HOSTNAME: opencti-ci-redis-master
  REDIS__MODE: single
  REDIS__PORT: 6379

testConnection: false

serviceMonitor:
  enabled: false

autoscaling:
  enabled: true

worker:
  enabled: true

  autoscaling:
    enabled: true

elasticsearch:
  fullnameOverride: opencti-ci-elasticsearch
  master:
    resourcesPreset: "medium"
  data:
    resourcesPreset: "medium"

minio:
  fullnameOverride: opencti-ci-minio

rabbitmq:
  fullnameOverride: opencti-ci-rabbitmq
  auth:
    erlangCookie: b25c953e-2193-4b8e-9f3b-9a3a5ba76d75

redis:
  fullnameOverride: opencti-ci-redis
