replicaCount: 1
fullnameOverride: opencti-ci

strategy:
  type: Recreate

env:
  APP__ADMIN__EMAIL: admin@opencti.io
  APP__BASE_PATH: "/"
  APP__TELEMETRY__METRICS__ENABLED: false
  APP__GRAPHQL__PLAYGROUND__ENABLED: false
  APP__GRAPHQL__PLAYGROUND__FORCE_DISABLED_INTROSPECTION: true

  ## OPENSEARCH
  ELASTICSEARCH__ENGINE_SELECTOR: opensearch
  ELASTICSEARCH__URL: http://opencti-ci-opensearch:9200

  ## STORAGE
  MINIO__ENDPOINT: opencti-ci-minio
  MINIO__PORT: 3900

  ## MESSAGE QUEUE
  RABBITMQ__HOSTNAME: opencti-ci-rabbitmq
  RABBITMQ__PORT_MANAGEMENT: 15672
  RABBITMQ__PORT: 5672
  RABBITMQ__USERNAME: user

  ## CACHE
  REDIS__HOSTNAME: opencti-ci-redis
  REDIS__MODE: single
  REDIS__PORT: 6379

envFromSecrets:
  APP__ADMIN__PASSWORD:
    name: opencti-ci-credentials
    key: APP__ADMIN__PASSWORD
  APP__ADMIN__TOKEN:
    name: opencti-ci-credentials
    key: APP__ADMIN__TOKEN
  APP__HEALTH_ACCESS_KEY:
    name: opencti-ci-credentials
    key: APP__HEALTH_ACCESS_KEY
  MINIO__ACCESS_KEY:
    name: opencti-ci-minio
    key: rootUser
  MINIO__SECRET_KEY:
    name: opencti-ci-minio
    key: rootPassword
  RABBITMQ__PASSWORD:
    name: opencti-ci-rabbitmq
    key: rabbitmq-password

secrets:
  - name: credentials
    data:
      APP__ADMIN__PASSWORD: iraLehfJu1NRnQgwIBeH
      APP__ADMIN__TOKEN: b1976749-8a53-4f49-bf04-cafa2a3458c1
      APP__HEALTH_ACCESS_KEY: f93747ff-2ea1-4717-900c-9df20b8e4429
  - name: minio
    data:
      rootUser: GKb81872b6e545a0c633918529
      rootPassword: a7c5a6bd2c62d9208b20f2671f25bceb7370f6fdc57b7c7a0ff00d4e7b8c0dae

testConnection: true

readyChecker:
  enabled: true
  retries: 30
  timeout: 5
  services:
  - name: opensearch
    port: 9200
  - name: minio
    port: 3900
  - name: rabbitmq
    port: 5672
  - name: redis
    port: 6379

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

startupProbe:
  enabled: false

lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 5"]

terminationGracePeriodSeconds: 20

service:
  type: ClusterIP
  port: 80
  targetPort: 4000
  protocol: TCP
  portName: http
  appProtocol: HTTP
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  publishNotReadyAddresses: false
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  trafficDistribution: PreferClose
  labels:
    environment: ci
  extraPorts:
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
      appProtocol: GRPC

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/os
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: opencti

##
# OPENCTI WORKER
worker:
  enabled: true

  readyChecker:
    enabled: true
    retries: 30
    timeout: 5

  lifecycle:
    preStop:
      exec:
        command: ["sh", "-c", "sleep 5"]

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi

  strategy:
    type: Recreate

  terminationGracePeriodSeconds: 20

  networkPolicy:
    enabled: true
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                name: opencti-ci
        ports:
          - protocol: TCP
            port: 4000

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/os
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: opencti
          opencti.component: worker

  dnsConfig:
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    searches: []
    options:
      - name: ndots
        value: "2"

  dnsPolicy: ClusterFirst

##
# OPENCTI CONNECTOR
connectorsGlobal:
  env:
    CONNECTOR_EXPOSE_METRICS: true

connectors:
  - name: opencti
    enabled: true
    replicas: 1

    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi

    serviceMonitor:
      enabled: false
      interval: 30s
      scrapeTimeout: 10s

    image:
      repository: opencti/connector-opencti
      pullPolicy: IfNotPresent

    readyChecker:
      enabled: true
      retries: 30
      timeout: 5

    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", "sleep 5"]

    terminationGracePeriodSeconds: 20

    deploymentAnnotations:
      ci: "true"
      prometheus.io/scrape: "true"
    podAnnotations:
      ci: "true"
    podLabels:
      ci: "true"
      opencti.component: connector

    env:
      CONNECTOR_ID: 399e6354-cc2c-4fe1-bb85-145a5bb043a9
      CONNECTOR_NAME: "OpenCTI"
      CONNECTOR_SCOPE: "marking-definition,identity,location"
      CONNECTOR_TYPE: EXTERNAL_IMPORT

    envFromFiles:
      - secretRef:
          name: opencti-ci-credentials

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/os
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: opencti
            opencti.component: connector

    dnsConfig:
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
      searches: []
      options:
        - name: ndots
          value: "2"

    dnsPolicy: ClusterFirst

    strategy:
      type: Recreate

##
# OPENSEARCH
opensearch:
  enabled: true
  fullnameOverride: opencti-ci-opensearch

  nodeGroup: ""
  opensearchJavaOpts: "-Xmx512M -Xms512M"
  singleNode: true

  config:
    opensearch.yml: |
      plugins.security.disabled: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  persistence:
    enabled: false

##
# MINIO
minio:
  fullnameOverride: opencti-ci-minio

    # -- When using Garage S3 -- Enable or disable automatic setup
  autosetup:
    enabled: true
    # zone: opencti
    # size: 1G
    version: v2.1.0

  rootUser: GKb81872b6e545a0c633918529
  rootPassword: a7c5a6bd2c62d9208b20f2671f25bceb7370f6fdc57b7c7a0ff00d4e7b8c0dae

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi

  persistence:
    enabled: true

  garage:
    s3:
      api:
        region: "us-east-1"

##
# RABBITMQ
rabbitmq:
  fullnameOverride: opencti-ci-rabbitmq

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi

  auth:
    password: K4we4CUebaRpISxWnMJn
    erlangCookie: b25c953e-2193-4b8e-9f3b-9a3a5ba76d75

  clustering:
    enabled: false

  networkPolicy:
    enabled: false

  persistence:
    enabled: false

##
# REDIS
redis:
  fullnameOverride: opencti-ci-redis

  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 256Mi

  extraArgs:
    - --maxmemory=256mb
    - --proactor_threads=1
    - --num_shards=1
  