{{- range .Values.worker.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "opencti.fullname" $ }}-{{ .name }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "0"
  labels:
    {{- include "opencti.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := .data }}
  {{- if regexMatch "\n" $value }}
  {{ $key }}: |
    {{ $value | nindent 4 | trim | b64enc }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{ end }}
