name: Lint and Test Helm Charts

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-test:
    permissions:
      contents: read
    uses: devops-ia/.github/.github/workflows/helm-lint-test.yml@main
